inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'bin/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

Rails:
  Enabled: true

Documentation:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 12

# 分岐の数。ガード句を多用しているとデフォルト 8 だと厳しい
Metrics/PerceivedComplexity:
  Max: 9

# 20 行超えるのは migration ファイル以外滅多に無い
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"

Layout/LineLength:
  Max: 198

Style/Documentation:
  Enabled: false

Style/EndOfLine: 
  EnforcedStyle: lf

GuardClause:
  MinBodyLength: 4

# メソッドの接頭辞にget_とかset_とかつけないルール
# すでにつけっちゃってて面倒とかだとfalseにする
Naming/AccessorMethodName:
  Enabled: false

Metrics/BlockLength:
  Max: 50
